const fs = require('fs-extra');
const path = require('path');

const srcDir = path.resolve(__dirname, '../src/assets');
const distDir = path.resolve(__dirname, '../dist/assets');

// Ensure dist directory exists
fs.ensureDirSync(distDir);

// Copy all assets
fs.copySync(srcDir, distDir, {
  overwrite: true,
  filter: (src) => {
    // Skip .br and .gz files as they will be generated by Vite
    return !src.endsWith('.br') && !src.endsWith('.gz');
  }
});

console.log('Assets copied successfully!'); 